# Numpy Code Challenge

### Selecting Even Indices

In this practice challenge, we ask you to create an ndarray from a given list and select the values located at even indexes.

values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

In [1]:
import numpy as np
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

x = np.array(values)
even = x[::2]
print(even)

[7 5 9 1 2]


### Selecting Odd Indices

In this practice challenge, we ask you to create an ndarray from a given list and select the values located at odd indexes.

values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

In [2]:
x = np.array(values)
odd = x[1::2]
print(odd)

[4 8 0 3 6]


### Reversing an Ndarray

In this practice challenge, we ask you create an ndarray from a given list and to reverse the order of its values.

values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

In [3]:
x = np.array(values)
reverse = x[::-1]
print(reverse)

[6 2 3 1 0 9 8 5 4 7]


### Getting the First Half

Write a function first_half() that, given a 1-dimensional array, returns an ndarray that contains the first half of the provided ndarray. If the input ndarray has an odd number of elements, you should exclude the middle element.

##### Testing Code
x = np.array([1, 2, 3, 4])
print(first_half(x))

x = np.array([1, 2, 3, 4, 5])
print(first_half(x))

In [4]:
def first_half(x):
    length = len(x)
    first_half = length // 2
    middle_number = np.median(x)
    middle_int_number = int(middle_number)
    middle_index_number = np.where(x == middle_int_number) 
    int_middle_index_number = middle_index_number[0]
    number = int_middle_index_number[0]
    if length % 2 == 0:
        return x[:first_half]
    else:
        return x[:number]

# Testing Code
x = np.array([1, 2, 3, 4])
print(first_half(x))

x = np.array([1, 2, 3, 4, 5])
print(first_half(x))

[1 2]
[1 2]


### Getting the Second Half

Write a function second_half() that, given a 1-dimensional array, returns an ndarray containing the second half of the provided ndarray. If the input ndarray has an odd number of elements, you should include the middle element.

##### Testing Code
x = np.array([1, 2, 3, 4])
print(first_half(x))

x = np.array([1, 2, 3, 4, 5])
print(first_half(x))

In [5]:
def second_half(y):
    length = len(y)
    second_half = length // 2
    middle_number = np.median(y)
    middle_int_number = int(middle_number)
    middle_index_number = np.where(y == middle_int_number) 
    int_middle_index_number = middle_index_number[0]
    number = int_middle_index_number[0]
    if length % 2 == 0:
        return y[second_half:]
    else:
        return y[number:]

# Testing Code
y = np.array([1, 2, 3, 4])
print(second_half(y))

y = np.array([1, 2, 3, 4, 5])
print(second_half(y))

[3 4]
[3 4 5]


### Concatenating Ndarrays

Use the np.concatenate() function to concatenate two ndarrays from the sequence below.

values1 = [5, 7, 4, 6, 3, 9]
values2 = [2, 1, 8, 0]

In [6]:
values1 = [5, 7, 4, 6, 3, 9]
values2 = [2, 1, 8, 0]

x = np.array(values1)
y = np.array(values2)
concat = np.concatenate([values1,values2])

print(concat)

[5 7 4 6 3 9 2 1 8 0]


### Mixing Ndarrays

Write a function mix() that, given two 1-dimensional arrays x and y, produces a new ndarray where:

1. The first half of its values corresponds to the first half of x (excluding the middle element if x has an odd length).

2. The second half of its values corresponds to the second half of y (including the middle element if y has an odd length).

##### Testing Code
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
z = mix(x, y)
print(z)

In [7]:
def mix(x, y):
    return np.concatenate([x[:len(x)//2], y[len(y)//2:]])

# Alternate Solution

#def mix(x,y):
#    return np.concatenate([first_half(x), second_half(y)])

# Testing Code
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
z = mix(x, y)

print(z)

[ 1  2  8  9 10]


### Reverse and Skip

In this practice challenge, we ask you to reverse the values of a 1-dimensional ndarray below while skipping every other value.

For example, if the ndarray is [1 2 3 4 5 6 7] then you need to obtain [7 5 3 1].

values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

In [8]:
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

x = np.array(values)
reverse_skip = x[::-2]

print(reverse_skip)

[6 3 0 8 4]


### Reversing a 2-D Array

In this practice challenge we want you to reverse a 2-dimensional ndarray. In other words, we want to obtain an ndarray where both the rows and the columns are in reverse order.

values = [
    [5, 6, 5, 5, 8, 9, 9], 
    [9, 5, 1, 4, 5, 9, 7], 
    [3, 9, 6, 2, 1, 2, 3], 
    [1, 7, 6, 7, 1, 7, 5], 
    [2, 1, 3, 8, 7, 8, 8], 
    [2, 9, 3, 6, 4, 6, 4]
]

In [9]:
values = [
    [5, 6, 5, 5, 8, 9, 9], 
    [9, 5, 1, 4, 5, 9, 7], 
    [3, 9, 6, 2, 1, 2, 3], 
    [1, 7, 6, 7, 1, 7, 5], 
    [2, 1, 3, 8, 7, 8, 8], 
    [2, 9, 3, 6, 4, 6, 4]
]

x = np.array(values)
reverse_2d = x[::-1, ::-1]

print(reverse_2d)

[[4 6 4 6 3 9 2]
 [8 8 7 8 3 1 2]
 [5 7 1 7 6 7 1]
 [3 2 1 2 6 9 3]
 [7 9 5 4 1 5 9]
 [9 9 8 5 5 6 5]]


### Row Selection

In this practice challenge, you'll write a function select_rows() that given a 2-dimensional array and a list of row indexes, returns a 2-dimensional array consisting only of those rows.

##### Testing Code
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
rows_1_4_3 = select_rows(x, [1, 4, 3])
print(rows_1_4_3)

In [10]:
def select_rows(x, row_indexes):
    return x[row_indexes, :]

# Testing Code
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
rows_1_4_3 = select_rows(x, [1, 4, 3])
print(rows_1_4_3)

[[ 5  6  7  8]
 [17 18 19 20]
 [13 14 15 16]]


### Column Selection

In this practice challenge, you'll write a function select_columns() that given a 2-dimensional array and a list of column indexes, returns a 2-dimensional array consisting only of those columns.

##### Testing Code

x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
cols_3_0 = select_columns(x, [3, 0])
print(cols_3_0)

In [11]:
def select_columns(x, col_indexes):
    return x[:, col_indexes]


# Testing Code
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
cols_3_0 = select_columns(x, [3, 0])
print(cols_3_0)

[[ 4  1]
 [ 8  5]
 [12  9]
 [16 13]
 [20 17]]


### Row Copies

In this practice challenge, you'll write a function copy_row_k_times() that given a 2-dimensional array, a row index row_index and a positive integer num_copies, creates a ndarray containing num_copies copies of row index row_index.
See the following example for clarity:

x = np.array([
    [ 1,  2,  3,  4], 
    [ 5,  6,  7,  8], 
    [ 9, 10, 11, 12]
])
row_k_times = copy_row_k_times(x, 1, 4)
print(row_k_times)

[[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]
 
As you can see, this function created 4 copies for the row from x that has with index 1

##### Testing code

x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]])
row_k_times = copy_row_k_times(x, 1, 4)
print(row_k_times)

In [12]:
def copy_row_k_times(x, row_index, num_copies):
    return x[[row_index] * num_copies]


# Testing Code
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]])
row_k_times = copy_row_k_times(x, 1, 4)
print(row_k_times)

[[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


### Selecting from a 2-D Array 1

In this practice challenge, we want you to select the entries highlighted in green of a 2-dimensional array.

![Image1](https://drive.google.com/file/d/1ujphPiOUtAZO73wzTidYcS7HCBBqNlBo/view?usp=sharing)

array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

In [13]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

x1 = array2d[:,1:3]
y1 = array2d[[0,2],:]
z1 = array2d[2,1:4]

print(x1)
print(y1)
print(z1)

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[12 13 14]


### Selecting from a 2-D Array 2

In this practice challenge, we want you to select the entries highlighted in green of a 2-dimensional array.

![Image2](https://drive.google.com/file/d/1GTFFw9vCSCPvR85sROK3pKtsh3tgzfDC/view?usp=sharing)

array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])


In [14]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

x2 = array2d[1::2, ::2]
y2 = array2d[::2, 1::2]
z2 = array2d[[0,2],1:4]

print(x2)
print(y2)
print(z2)

[[ 6  8 10]
 [16 18 20]]
[[ 2  4]
 [12 14]]
[[ 2  3  4]
 [12 13 14]]


### Selecting from a 2-D Array 3

In this practice challenge, we want you to select the entries highlighted in green of a 2-dimensional array.

![Image3](https://drive.google.com/file/d/1Gq6flsy7oFWysmApTfqAjfNasLBNMbr9/view?usp=sharing)

array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])


In [15]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

x3 = array2d[:,2:]
y3 = array2d[1:,1:]
z3 = array2d[:3,:4]

print(x3)
print(y3)
print(z3)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


### Swapping Rows

In this practice challenge, we want you to write a function swap_rows() that given a 2-dimensional array and two row indexes, swaps those two rows.

Example:

x = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])
swap_rows(x, 0, 1)
print(x)

[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
 
 Note that the function does not return anything, it modifies the given ndarray directly.
 
 ##### Testing Code
 
 x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_rows(x, 0, 2)
print(x)

In [16]:
def swap_rows(x,row_index1,row_index2):
    x[[row_index1, row_index2]] = x[[row_index2, row_index1]]


# Testing Code
x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_rows(x, 0, 2)
print(x)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


### Swapping Columns

In this practice challenge, we want you to write a function swap_cols() that given a 2-dimensional array and two column indexes, swaps those two columns.

Example:

x = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])
swap_cols(x, 0, 1)
print(x)

[[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]]
 
Note that the function does not return anything, it modifies the given ndarray directly.

##### Testing Code

x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_cols(x, 0, 1)
print(x)


In [17]:
def swap_cols(x,col_index1,col_index2):
    x[:, [col_index1, col_index2]] = x[:, [col_index2, col_index1]]


# Testing Code
x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_cols(x, 0, 1)
print(x)

[[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]]
